# .github/workflows/docker-build.yml
name: Build n8n with Global Agent

on:
  workflow_dispatch:
    inputs:
      n8n_version:
        description: 'n8n version to build'
        required: true
        default: 'latest'
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     n8n_version: [ "1.50.2", "1.81.4", "1.82.1" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          # build-args: |
          #   N8N_VERSION=${{ matrix.n8n_version }}
          # tags: ghcr.io/${{ github.repository_owner }}/n8n-ga:${{ matrix.n8n_version }}
          build-args: |
            N8N_VERSION=${{ github.event.inputs.n8n_version }}
          tags: ghcr.io/orrocyber/n8n-ga:${{ github.event.inputs.n8n_version }}
          push: true
          platforms: linux/amd64,linux/arm64/v8
